### ISSUE TITLE
state type HUE not supported

### ISSUE THREAD

**Issue by DutchmanNL** [TA2k/ioBroker.iot#1]
Used for example in Ikea lightbulbs : 

```
Cannot auto convert tradfri.0.G-153254. Type hue is not available, yet. If you need the state please add him manually
```

**Comment by TA2k** [comment]
I added hue type. Please test it. I implemented without testing.

**Comment by DutchmanNL** [comment]
after testing the new version (from GitHub) I added the Ikea lights again.

Wenn i open the item in googlehome app the iot adapter crashes : 

```

2019-09-03 10:55:06.706 - error: iot.0 uncaught exception: Cannot set property 'spectrumRgb' of undefined
--
2019-09-03 10:55:06.706 - error: iot.0 TypeError: Cannot set property 'spectrumRgb' of undefined
at Object.keys.forEach.attr (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:2048:85)
at Array.forEach ()
at devices.forEach.dev (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:2009:44)
at Array.forEach ()
at getStates.states (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:2003:25)
at GoogleHome.getStates (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:1980:13)
at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:1985:41)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)
2019-09-03 10:55:06.709 - info: iot.0 terminating
2019-09-03 10:55:06.724 - error: Caught by controller[0]: TypeError: Cannot set property 'spectrumRgb' of undefined
2019-09-03 10:55:06.725 - error: Caught by controller[0]: at Object.keys.forEach.attr (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:2048:85)
2019-09-03 10:55:06.725 - error: Caught by controller[0]: at Array.forEach ()
2019-09-03 10:55:06.725 - error: Caught by controller[0]: at devices.forEach.dev (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:2009:44)
2019-09-03 10:55:06.725 - error: Caught by controller[0]: at Array.forEach ()
2019-09-03 10:55:06.725 - error: Caught by controller[0]: at getStates.states (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:2003:25)
2019-09-03 10:55:06.725 - error: Caught by controller[0]: at GoogleHome.getStates (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:1980:13)
2019-09-03 10:55:06.725 - error: Caught by controller[0]: at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:1985:41)
2019-09-03 10:55:06.725 - error: Caught by controller[0]: at runCallback (timers.js:705:18)
2019-09-03 10:55:06.725 - error: Caught by controller[0]: at tryOnImmediate (timers.js:676:5)
2019-09-03 10:55:06.725 - error: Caught by controller[0]: at processImmediate (timers.js:658:5)
2019-09-03 10:55:06.725 - error: host.ioBroker instance system.adapter.iot.0 terminated with code 0 (OK)


```

**Comment by TA2k** [comment]
Please install and test again

**Comment by DutchmanNL** [comment]
> Please install and test again

installed from git, execute upload & adapter reboot : 

```

2019-09-03 12:10:33.686 - error: iot.0 uncaught exception: Cannot set property 'spectrumRgb' of undefined
--
2019-09-03 12:10:33.686 - error: iot.0 TypeError: Cannot set property 'spectrumRgb' of undefined
at Object.keys.forEach.attr (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:2048:85)
at Array.forEach ()
at devices.forEach.dev (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:2009:44)
at Array.forEach ()
at getStates.states (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:2003:25)
at GoogleHome.getStates (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:1980:13)
at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:1985:41)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)
2019-09-03 12:10:33.688 - info: iot.0 terminating
2019-09-03 12:10:33.707 - error: Caught by controller[0]: TypeError: Cannot set property 'spectrumRgb' of undefined
2019-09-03 12:10:33.707 - error: Caught by controller[0]: at Object.keys.forEach.attr (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:2048:85)
2019-09-03 12:10:33.707 - error: Caught by controller[0]: at Array.forEach ()
2019-09-03 12:10:33.707 - error: Caught by controller[0]: at devices.forEach.dev (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:2009:44)
2019-09-03 12:10:33.707 - error: Caught by controller[0]: at Array.forEach ()
2019-09-03 12:10:33.707 - error: Caught by controller[0]: at getStates.states (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:2003:25)
2019-09-03 12:10:33.707 - error: Caught by controller[0]: at GoogleHome.getStates (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:1980:13)
2019-09-03 12:10:33.707 - error: Caught by controller[0]: at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.iot/lib/GoogleHome.js:1985:41)
2019-09-03 12:10:33.708 - error: Caught by controller[0]: at runCallback (timers.js:705:18)
2019-09-03 12:10:33.708 - error: Caught by controller[0]: at tryOnImmediate (timers.js:676:5)
2019-09-03 12:10:33.708 - error: Caught by controller[0]: at processImmediate (timers.js:658:5)
2019-09-03 12:10:33.708 - error: host.ioBroker instance system.adapter.iot.0 terminated with code 0 (OK)
2019-09-03 12:10:33.708 - info: host.ioBroker Restart adapter system.adapter.iot.0 because enabled
```

**Comment by TA2k** [comment]
Sorry try again.

**Comment by DutchmanNL** [comment]
solved 👍
